channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3.10.6
  # - pandas=1.5.3
  # - matplotlib=3.7.2
  # - datasets=2.13.1
  # - transformers=4.30.2
  - pytorch
  - gcc=13.1.0
  - pytorch-cuda=12.1
  - cuda-compiler=12.1
  # - deepspeed=0.9.5
  # - pydantic=1.10.11
  - pip:
    # - azureml-mlflow==1.49.0
    # - func-to-script==0.1.0
    # - mlflow-skinny==2.2.2
    # - pytorch-accelerated==0.1.47
    # - peft==0.4.0
    # - bitsandbytes==0.41.0
    # - scipy==1.11.1
    - packaging
    - numpy